### ISSUE TITLE
Support host for request stub

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#24]
- [ ] Implement #23 

needs multiple kakapo server support #23

**Comment by MP0w** [comment]
Can we discuss this here?

**Comment by joanromano** [comment]
@MP0w would make sense to introduce Routers here? Server will handle a static array of Routers instead of a `private static var routes: [String : Route]`, and forward the static protocol methods to each of those.

The users asks the Server to register a new Router with a given host, and gets it. Then we move all the `get, post, del, put, patch...` methods to be instance methods of the Routers.

Guess the idea needs more refining and a bit proposed code solution here, but just to have a general picture for now.

**Comment by MP0w** [comment]
@joanromano yes for #23 we probably need something like that...
"Server will handle a static array of Routers" careful not to leak Routers

**Comment by joanromano** [comment]
"careful not to leak Routers" I'll do my best 👯

**Comment by MP0w** [comment]
related to https://github.com/devlucky/Kakapo.js/issues/43
